### ISSUE TITLE
Pass seed as parameter

### ISSUE THREAD

**Issue by aviggiano** [crytic/medusa#201]
Hello,

Is it possible to pass a seed parameter to the fuzzer? I can't find it in the code.

Thanks

**Comment by Xenomega** [comment]
Medusa uses a seed internally, but does not expose it because re-use of the seed is not predictable, due to parallelization. 

e.g. you may have multiple workers/threads in the fuzzer that report results at the same time and encounter race conditions, despite using the same seed, which will change execution moving forward. We could expose this but then there will be the expectation this will behave the same each time. To give that guarantee would mean constraining the fuzzer performance by enforcing the same parallelized control flow through locking.

**Comment by aviggiano** [comment]
Understood, thanks for answer.

What about a single worker run, would it make sense to expose the seed? I'd like to have this feature for predictable benchmarking purposes.

**Comment by 0xalpharush** [comment]
Chiming in here.. I don't think a statistically sound benchmark should need determinism to be reproducible but rather should do something like compare 20 fuzz campaigns that were run for 24 hours (mirroring the design of [FuzzBench](https://storage.googleapis.com/pub-tools-public-publication-data/pdf/64574e1a7cfc9456c273ce03574dacfcd6ad9d54.pdf)). Relying on a seed may even bias this i.e. it positively or negatively effects the coverage reported for a given campaign. This is outlined in some [prior research](https://dl.acm.org/doi/pdf/10.1145/3243734.32438040) cited by the FuzzBench paper. Fwiw, there's also concern whether the coverage reporting is reliable unless it's performed by the same tool which is unfortunately not available for Solidity and native to each fuzzer (Echidna, Medusa, Foundry, etc).

**Comment by aviggiano** [comment]
@0xalpharush Thanks for the great explanation

Running N-fuzz campaigns for long H hours is already what I was doing when comparing foundry to echidna (measuring performance by ["time to break invariants"](https://vixra.org/pdf/2307.0103v1.pdf), but there I also used the same set of seed values for each test, but I guess this might not be really necessary. 

I'll close this issue now, thanks
