### ISSUE TITLE
Possible error with `prankHere`

### ISSUE THREAD

**Issue by hexshire** [crytic/medusa#435]
`prankHere` cheat code does not work as intended when trying to deploy contracts with a given address.

# Proof of concept
```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.25;

interface IStdCheats {
  // Computes address for a given private key
  function addr(uint256 privateKey) external returns (address);

  // Sets the *next* call's msg.sender to be the input address
  function prank(address) external;

  // Set msg.sender to the input address until the current call exits
  function prankHere(address) external;
}

contract Ownable {
  address public owner;

  constructor() {
    owner = msg.sender;
  }
}

contract Fuzz {
  IStdCheats constant cheats = IStdCheats(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D);

  Ownable public one;
  Ownable public two;
  Ownable public three;

  function test() public {
    address owner = cheats.addr(0x123);

    // Control test with simple prank
    cheats.prank(owner);
    one = new Ownable();

    cheats.prankHere(owner);
    two = new Ownable();
    three = new Ownable();

    assert(one.owner() == owner);
    assert(two.owner() == owner);
    assert(three.owner() == owner);
  }
}
```
![image](https://github.com/user-attachments/assets/b9e2a722-2aa4-4b40-9701-b86d10ac571d)

**Comment by anishnaik** [comment]
Hey @hexshire so we did some digging and this is actually the expected behavior of the `prankHere` function. So `prankHere` actually changes the `msg.sender` in the _current call scope_. Thus, when you run `two = new Ownable()`, the `msg.sender` in that case will actually be the `Fuzz` contract. So `prank` is best to use if you want to prank the `msg.sender` for an external contract call. If you want to prank the `msg.sender` for the current call, you should use `prankHere`. Does that make sense?

**Comment by hexshire** [comment]
@anishnaik oh, makes sense. I was expecting something similar to `startPrank`. Thanks!!

**Comment by anishnaik** [comment]
Yea, we should probably improve the documentation around this. We should definitely also implement `startPrank` and `endPrank`.
